package com.alex.xdw.ui.theme

import androidx.compose.ui.graphics.Color

val AppleBlue = Color(0xFF0071E3)
val AppleBlueSoft = Color(0xFFDCEBFF)
val AppleBackground = Color(0xFFF5F5F7)
val AppleSurface = Color(0xFFFFFFFF)
val AppleSurfaceRaised = Color(0xFFEDEDF2)
val AppleTextPrimary = Color(0xFF1D1D1F)
val AppleTextSecondary = Color(0xFF6E6E73)
val AppleOutline = Color(0xFFD2D2D7)
val AppleDanger = Color(0xFFD83A3A)

val SupabaseGreen = Color(0xFF3ECF8E)
val SupabaseGreenDeep = Color(0xFF00C573)
val SupabaseBackground = Color(0xFF171717)
val SupabaseSurface = Color(0xFF0F0F0F)
val SupabaseSurfaceRaised = Color(0xFF202020)
val SupabaseTextPrimary = Color(0xFFFAFAFA)
val SupabaseTextSecondary = Color(0xFFB4B4B4)
val SupabaseOutline = Color(0xFF2E2E2E)
val SupabaseDanger = Color(0xFFE85D5D)

val AirtableBlue = Color(0xFF2D7FF9)
val AirtableCyan = Color(0xFFDFF4FF)
val AirtableBackground = Color(0xFFF7F9FC)
val AirtableSurface = Color(0xFFFFFFFF)
val AirtableSurfaceRaised = Color(0xFFF1F5FB)
val AirtableTextPrimary = Color(0xFF1F2A37)
val AirtableTextSecondary = Color(0xFF5B6778)
val AirtableOutline = Color(0xFFD5DFEC)

val FigmaPurple = Color(0xFF7B61FF)
val FigmaMint = Color(0xFFDDF7F0)
val FigmaBackground = Color(0xFFF8F9FB)
val FigmaSurface = Color(0xFFFFFFFF)
val FigmaSurfaceRaised = Color(0xFFF0F2F7)
val FigmaTextPrimary = Color(0xFF12161F)
val FigmaTextSecondary = Color(0xFF697180)
val FigmaOutline = Color(0xFFD7DCE5)

val AirbnbCoral = Color(0xFFFF5A5F)
val AirbnbRose = Color(0xFFFFE7EA)
val AirbnbBackground = Color(0xFFFFF8F8)
val AirbnbSurface = Color(0xFFFFFFFF)
val AirbnbSurfaceRaised = Color(0xFFFFF0F1)
val AirbnbTextPrimary = Color(0xFF222222)
val AirbnbTextSecondary = Color(0xFF6B6B6B)
val AirbnbOutline = Color(0xFFFFD5D9)

val HybridBlue = Color(0xFF3A78F2)
val HybridGreen = Color(0xFF1FBF92)
val HybridBackground = Color(0xFFF4F7FB)
val HybridSurface = Color(0xFFFFFFFF)
val HybridSurfaceRaised = Color(0xFFEAF0F7)
val HybridTextPrimary = Color(0xFF162033)
val HybridTextSecondary = Color(0xFF667085)
val HybridOutline = Color(0xFFD7E0EC)
